language: c
compiler: gcc
script: make test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq valgrind

env:
  - XXH_TRAVIS_CI_ENV=-m32
  - XXH_TRAVIS_CI_ENV=-m64

matrix:
  fast_finish: true
